apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongo-deployment
 namespace: default
spec:
 replicas: 2
 selector:
  matchLabels:
   app: mongo
 template:
  metadata:
   labels:
    app: mongo
  spec:
   containers:
   - image: mongo
     name: mongodb-container	
     ports:
     - containerPort: 27017
